spring:
  application:
    name: stats-server
  datasource:
    url: jdbc:postgresql://localhost:6431/stat_db
    username: stat_user
    password: stat_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

server:
  port: 9090
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health, info